services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sales_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@AdminSql
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: